# Generated by chatGPT
# Kind of crazy to me, only had to make the grammer a raw string to solve some issue with newlines in the grammar?
# Solution found at: https://stackoverflow.com/questions/70966085/how-does-one-match-eol-newline-with-lark

from lark import Lark

httpd_config_grammar = r'''
    config_file: directive+
    directive: directive_name directive_parameters
    directive_name: IDENTIFIER
    directive_parameters: parameter+
    parameter: value | STRING
    value: /[^\s\r\n]+/
    IDENTIFIER: /[a-zA-Z_][a-zA-Z0-9_-]*/
    STRING: ESCAPED_STRING | SINGLE_QUOTED_STRING
    ESCAPED_STRING: /"([^"\\]|\\.)*"/
    SINGLE_QUOTED_STRING: /'([^'\\]|\\.)*'/
    %import common.WS
    %ignore WS
'''

# Initialize Lark parser with the Apache HTTPd config grammar
parser = Lark(httpd_config_grammar, start='config_file')

# Test parsing
config_file = '''
    ServerName "example.com"
    DocumentRoot "/var/www/html"
    <Directory "/var/www/html">
        AllowOverride None
        Require all granted
    </Directory>
'''

parsed_config = parser.parse(config_file)
print(parsed_config)