# Largely Generated by chatGPT
# Kind of crazy to me, only had to make the grammer a raw string to solve some issue with newlines in the grammar?
# Solution found at: https://stackoverflow.com/questions/70966085/how-does-one-match-eol-newline-with-lark

from lark import Lark

# Load the grammar
grammar = 'grammars/config.lark'
with open(grammar, 'r') as grammar_file:
  httpd_config_grammar = grammar_file.read()

# Initialize Lark parser with the Apache HTTPd config grammar
parser = Lark(httpd_config_grammar, start='config_file')

# Test parsing
config_file = '''
    # Single-line Comment
    # Multi-\
line Comment

    ServerName "example.com"
    DocumentRoot "/var/www/html"
    <Directory "/var/www/html">
        AllowOverride None
        Require all granted
    </Directory>
'''

parsed_config = parser.parse(config_file)
print(parsed_config)
print ("--------------------")
print(config_file)
print ("--------------------")
print(parsed_config.pretty())